// <auto-generated />
using System;
using FilmesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmesAPI.Migrations
{
    [DbContext(typeof(FilmeContext))]
    [Migration("20260106180304_AdicionandoAtoresElenco")]
    partial class AdicionandoAtoresElenco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FilmesAPI.Models.Ator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimeiroNome")
                        .HasColumnType("longtext");

                    b.Property<string>("UltimoNome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Atores");
                });

            modelBuilder.Entity("FilmesAPI.Models.Elenco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("IdAtor")
                        .HasColumnType("int");

                    b.Property<int?>("IdFilme")
                        .HasColumnType("int");

                    b.Property<string>("Papel")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdAtor");

                    b.HasIndex("IdFilme");

                    b.ToTable("ElencoFilme");
                });

            modelBuilder.Entity("FilmesAPI.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("FilmesAPI.Models.FilmesGenero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("IdFilme")
                        .HasColumnType("int");

                    b.Property<int?>("IdGenero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdFilme");

                    b.HasIndex("IdGenero");

                    b.ToTable("FilmesGenero");
                });

            modelBuilder.Entity("FilmesAPI.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Genero");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("FilmesAPI.Models.Elenco", b =>
                {
                    b.HasOne("FilmesAPI.Models.Ator", "Ator")
                        .WithMany("ElencoFilme")
                        .HasForeignKey("IdAtor");

                    b.HasOne("FilmesAPI.Models.Filme", "Filme")
                        .WithMany("ElencoFilme")
                        .HasForeignKey("IdFilme")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Ator");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("FilmesAPI.Models.FilmesGenero", b =>
                {
                    b.HasOne("FilmesAPI.Models.Filme", "Filme")
                        .WithMany("FilmesGenero")
                        .HasForeignKey("IdFilme")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FilmesAPI.Models.Genero", "Genero")
                        .WithMany("FilmesGenero")
                        .HasForeignKey("IdGenero");

                    b.Navigation("Filme");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("FilmesAPI.Models.Ator", b =>
                {
                    b.Navigation("ElencoFilme");
                });

            modelBuilder.Entity("FilmesAPI.Models.Filme", b =>
                {
                    b.Navigation("ElencoFilme");

                    b.Navigation("FilmesGenero");
                });

            modelBuilder.Entity("FilmesAPI.Models.Genero", b =>
                {
                    b.Navigation("FilmesGenero");
                });
#pragma warning restore 612, 618
        }
    }
}
